name: Server-Core
author: plocki
version: 1.0
api-version: 1.16
main: de.plocki.main.Main
commands:
   day:
   night:
   eco:
   money:
   sun:
   feed:
   coins:
   coin:
   geld:
   euro:
   dollar:
   chatcolor:
   servercoreversion:
   scv:
   server-core-version:
   wb:
   workbench:
   server-core-ver:
   servercorever:
   gm:
   gamemode:
   msg:
   ci:
   clear:
   vc:
   votecoin:
   votecoins:
   tphere:
   ecovote:
   dailyreward:
   dr:
   dailyr:
   reward:
   ec:
   enderchest:
   enderc:
   fly:
   flight:
   freeze:
   f:
   globalmute:
   gmute:
   heal:
   invsee:
   inv:
   job:
   jobs:
   msg:
   pay:
   rename:
   rep:
   repair:
   sign:
   tp:
   tpa:
   tpaall:
   tpahere:
   tpaccept:
   tphere:
   tpaaccept:
   vanish:
   v:
   cc:
   clearchat:
   chatclear:
   ff:
   forcefield:
   skull:
   head:
   kopf:
   pm:
